name: Run Unit Tests

on:
  push:
    branches: [dev, development]

jobs:
  test:
    name: Run CDK Tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - name: Action Checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: npm install 
      - name: Run Tests
        run: npm test
        with:
            aws-account-id: ${{ secrets.AWS_ACCOUNT_ID }}
            aws-region: ${{ secrets.AWS_REGION }}